### ISSUE TITLE
FP + TP + FN != injected bugs 

### ISSUE THREAD

**Issue by minhhn2910** [cassc/SolidiFI-benchmark#3]
Bug report file : https://gist.github.com/minhhn2910/b105f708882b6cd6575d2e1e135a7e0b
Results: 
```
buggy_contracts/Overflow-Underflow/buggy_32.sol
Injected: 21   FP: 0    TP: 19   FN: 0  
```
Expected: injected = TP + FN + FP or the reason behind the difference.

**Comment by minhhn2910** [comment]
Since TP maybe more than injected. We need another column TP_range with matching range count as TP, similar to how SolidiFI treat other tools. For fair comparison.

**Comment by cassc** [comment]
Hi @minhhn2910 , `TP_range` or true positives counted from injected bugs is just `number of injected - FN`. 
Updated in this [PR](https://github.com/cassc/SolidiFI-benchmark/pull/5)

**Comment by cassc** [comment]
> Expected: injected = TP + FN + FP or the reason behind the difference.

This isn't true, `FP` can be any number, not necessarily smaller than the number of injected bugs
